gitops-runtime:
  global:
    codefresh:
      accountId: 67da9754c6a369df5c795fc2
      userToken:
        secretKeyRef:
          name: codefresh-user-token
          key: token
    runtime:
      name: codefresh
